CREATE DATABASE TrilhaCrescimento;
GO

USE TrilhaCrescimento;
GO

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    senha VARCHAR(255),
    google_id VARCHAR(255) UNIQUE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
GO

create table public.times (
  id bigint generated by default as identity not null,
  nome character varying not null,
  constraint times_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO "public"."times" ("id", "nome") 
    VALUES (1, 'Relacionamento'), (2, 'Experiência'), (3, 'Logística'), (4, 'Produção'), (5, 'Facilitador'), (6, 'Discipulado'), (7, 'Kids');
GO